import type {Metadata} from "next";
import {ThemeProvider} from "next-themes";
import {Inter} from "next/font/google";
import "./globals.css";
import {AuthContextProvider} from "@/context/auth-provider";
import {ConvexClientProvider} from "@/context/convex-provider";
import {ReactNode} from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    // `suppressHydrationWarning` only affects the html tag,
    // and is needed by `ThemeProvider` which sets the theme
    // class attribute on it
    <html lang="en" suppressHydrationWarning>
    <body className={inter.className}>
    <ThemeProvider attribute="class">
      <ConvexClientProvider>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </ConvexClientProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
