services:
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
  db:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
