name = "edge-rocketseat"
main = "src/index.ts"
compatibility_date = "2022-06-03"

[vars]
UPSTASH_REDIS_REST_URL="https://global-solid-raccoon-30364.upstash.io"

# [secrets]
# UPSTASH_REDIS_REST_TOKEN
