version: "3.9"

services:
  database_ignite:
      image: 'bitnami/postgresql'
      container_name: database_ignite
      restart: always
      ports:
        - '5432:5432'
      environment:
        - POSTGRESQL_USERNAME=docker
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=rentx
      volumes:
        - 'postgresql_data:/bitnami/postgresql'

  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  postgresql_data:
    driver: local
